## 什么是异常

异常 是在程序执行期间发生的事件，它会破坏程序指令的正常流程，或者简单地说，任何使你的测试用例在执行之间停止的问题都是异常。

## 错误与异常的区别

错误 “表示合理的应用程序不应尝试捕获的严重问题” 。

异常 “表示合理的应用程序可能想要捕获的条件”。

每当执行语句时发生 错误，都会创建一个异常对象 ，然后程序的正常流程停止，并尝试找到可以处理引发的异常的人。异常对象包含了很多调试信息，比如方法层次结构、异常发生的行号、异常类型等。当一个方法发生异常时，会调用创建异常对象并交给运行环境的过程 “抛出异常”。

## 什么是异常处理

异常处理 是指对编程应用程序和通信错误的预测、检测和解决。 它是处理异常对象并通过让我们有机会对其采取行动来帮助我们的代码块。

## 为什么异常处理很重要

1.  想一想你遇到异常并且想要在日志中打印一些自定义消息以便整个团队都能理解的情况。
2.  在某些情况下，你可能只想吃掉异常并希望你的测试在执行的其余部分继续进行。
3.  如果你想在发生特定异常时执行一系列步骤，例如，如果你因为产品缺货而出现异常，则该产品不再显示在页面上并且你希望你使用其他可用产品在页面上。
4.  如果你想在 Selenium 中处理某种异常，例如ElementNotSelectableException、 ElementNotVisibleException、NoSuchElementException 等异常。

## Selenium 中的不同异常

Selenium 文档中提到了完整的异常列表，你在测试过程中可能会遇到也可能不会遇到这些异常。

### 最常见的异常：

1.  NoSuchElementException：FindBy 方法找不到元素。
2.  StaleElementReferenceException：这表明该元素不再出现在 DOM 页面上。
3.  TimeoutException：这表明执行失败，因为命令没有在足够的时间内完成。
4.  ElementNotVisibleException：抛出以指示尽管元素存在于 DOM 中，但它不可见，因此无法与之交互
5.  ElementNotSelectableException：抛出表示元素可能被禁用，因此无法选择。

## 如何处理异常

Try/Catch ：一种方法使用try 和 catch 关键字的组合来捕获异常 Try 是块的开始， Catch 在 try 块的末尾以处理异常。try/catch块放置在可能产生异常的代码周围。try/catch 块中的代码称为受保护代码，使用 try/catch 的语法如下所示：

```java
try{
    // Some code
}catch(Exception e){
    // Code for Handling the exception
    }
```

多个 Catch 块： 一个try块后面可以跟 多个 catch 块。就像我之前说的，有多个异常，你可以在一个代码块上预期不止一种类型的异常，如果你想用单独的代码块分别处理每种类型的异常。多个 catch 块的语法如下所示：

```java
try{
    //Some code
}catch(ExceptionType1 e1){
    //Code for Handling the Exception 1
}catch(ExceptionType2 e2){
    //Code for Handling the Exception 2
   }
```

catch 块的数量没有限制，可以使用两个以上。你可能想知道它是如何工作的。很简单，如果受保护的代码发生异常，异常会被抛到列表中的第一个catch块。如果抛出的异常与ExceptionType1 匹配，它会在那里被捕获并执行同一异常块下的代码。如果不是，则异常传递到第二个 catch 语句并继续这样。

注意： 如果异常与任何异常类型都不匹配并落在所有捕获中，则当前方法停止执行并抛出异常。这就是为什么建议最后也包含默认异常，这样万一异常失败，它可以由默认异常处理。

抛出： 有时我们希望在我们的代码中显式地产生异常，例如在Selenium Automation Framework中，大多数时候我们打印自己写的日志，一旦捕获到一个异常，我们就需要将该异常抛回给系统，以便测试用例可以终止。 throw 关键字用于将异常抛出给运行时处理。

Throws： 当我们在方法中抛出任何异常而不处理它时，我们需要 在方法签名中使用throws 关键字 来让调用程序知道该方法可能抛出的异常。

```java
// Method Signature\
public static void anyFunction() throws Exception{
    try{
        // write your code here    
    }catch (Exception e){
        // Do whatever you wish to do here
        // Now throw the exception back to the system
        throw(e);
        }
    }
```

多个异常：可以在 throws 子句中处理多个异常。

```java
public static void anyFunction() throws ExceptionType1, ExceptionType2{
    try{
         //Some code 
     }catch(ExceptionType1 e1){ 
         //Code for Handling the Exception 1
     }catch(ExceptionType2 e2){
         //Code for Handling the Exception 2
     }
```

Finally： finally关键字用于创建跟在 try 块之后的代码块。finally 代码块始终执行，无论是否发生异常。

```java
try{
    //Protected code
}catch(ExceptionType1 e1){
    //Catch block
}catch(ExceptionType2 e2){
    //Catch block
}catch(ExceptionType3 e3){
    //Catch block
}finally{
    //The finally block always executes.
    }
```

## 框架中的异常处理

你的 Selenium 测试应该能够失败，但不是因为抛出的异常。如果你的测试因异常而失败，那么很可能你没有异常处理。通过这样做，你没有机会在测试结束时清理 WebDriver 对象。

测试应该仅在你的条件下失败，例如，你永远不应该得到像NullPointerException这样的异常，但是如果你得到像ElementNotFoundException这样的异常，那么捕获异常、停止进一步执行并以合乎逻辑的方式。

正如我上面所说，当我们遇到任何异常时，最好打印错误日志，以便进行调查。抛出错误取决于框架到框架，因为如果你捕捉到异常并将异常抛回主程序，那么主程序中也有必要有一个try catch块，这样才能以适当的方式关闭测试用例. 如果不处理异常，测试用例就停在那里，不会执行批运行的其他测试用例。

## 本框架中的异常处理

正如我所说，这完全取决于你要如何处理异常，因此没有必要遵循这种方法。你可以按照自己的方式进行。我创建了一个“public static boolean bResult;” 在我的主驱动程序脚本中添加变量，并在每个测试用例和每个测试步骤开始时将其值设置为“true” 。意味着我们在主驱动程序脚本中有两个循环，外循环用于测试用例，内循环用于测试步骤。因此，在开始每个新的测试用例和测试步骤时，我将此变量值设置为“true”。其背后的想法是在出现任何异常时将值从“true”更改为“false” 。 异常将被try catch 捕获块和将值从“true”更改为“false”的语句将驻留在该块中。例如：

```java
public static void openBrowser(String object){
	try{
	Log.info("Opening Browser");
	driver=new FirefoxDriver();
	}catch(Exception e){
		Log.info("Not able to open Browser --- " + e.getMessage());
		DriverScript.bResult = false;
		}
	}
```

这意味着bResult值将仅在出现异常时设置为'false'，否则它将始终保持为'true'。所以现在我们只需要在主驱动程序脚本中匹配bResult的值。如果为真，则执行下一步，如果为假，则停止测试步骤和测试用例，并继续进行下一个测试用例。

一旦在框架中设置了异常处理，ActionKeyword 类和 ExcelUtils 类将如下所示：

### 动作关键字类

```java
package config;

import java.util.concurrent.TimeUnit;
import static executionEngine.DriverScript.OR;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import executionEngine.DriverScript;
import utility.Log;

public class ActionKeywords {

		public static WebDriver driver;

	public static void openBrowser(String object){
		try{
		Log.info("Opening Browser");
		driver=new FirefoxDriver();
		
		//This block will execute only in case of an exception
		}catch(Exception e){
			//This is to print the logs - Method Name & Error description/stack
			Log.info("Not able to open Browser --- " + e.getMessage());
			//Set the value of result variable to false
			DriverScript.bResult = false;
			}
		}

	public static void navigate(String object){
		try{
			Log.info("Navigating to URL");
			driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
			driver.get(Constants.URL);
		}catch(Exception e){
			Log.info("Not able to navigate --- " + e.getMessage());
			DriverScript.bResult = false;
			}
		}

	public static void click(String object){
		try{
			Log.info("Clicking on Webelement "+ object);
			driver.findElement(By.xpath(OR.getProperty(object))).click();
		 }catch(Exception e){
 			Log.error("Not able to click --- " + e.getMessage());
 			DriverScript.bResult = false;
         	}
		}

	public static void input_UserName(String object){
		try{
			Log.info("Entering the text in UserName");
			driver.findElement(By.xpath(OR.getProperty(object))).sendKeys(Constants.UserName);
		 }catch(Exception e){
			 Log.error("Not able to Enter UserName --- " + e.getMessage());
			 DriverScript.bResult = false;
		 	}
		}

	public static void input_Password(String object){
		try{
			Log.info("Entering the text in Password");
			driver.findElement(By.xpath(OR.getProperty(object))).sendKeys(Constants.Password);
		 }catch(Exception e){
			 Log.error("Not able to Enter Password --- " + e.getMessage());
			 DriverScript.bResult = false;
		 	}
		}

	public static void waitFor(String object) throws Exception{
		try{
			Log.info("Wait for 5 seconds");
			Thread.sleep(5000);
		 }catch(Exception e){
			 Log.error("Not able to Wait --- " + e.getMessage());
			 DriverScript.bResult = false;
         	}
		}

	public static void closeBrowser(String object){
		try{
			Log.info("Closing the browser");
			driver.quit();
		 }catch(Exception e){
			 Log.error("Not able to Close the Browser --- " + e.getMessage());
			 DriverScript.bResult = false;
         	}
		}

	}
```

### Excel 实用程序类：

```java
package utility;

import java.io.FileInputStream;
import java.io.FileOutputStream;

import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFRow;

import config.Constants;
import executionEngine.DriverScript;
    public class ExcelUtils {
			private static XSSFSheet ExcelWSheet;
			private static XSSFWorkbook ExcelWBook;
			private static org.apache.poi.ss.usermodel.Cell Cell;
			private static XSSFRow Row;

		public static void setExcelFile(String Path) throws Exception {
			try {
				FileInputStream ExcelFile = new FileInputStream(Path);
				ExcelWBook = new XSSFWorkbook(ExcelFile);
			} catch (Exception e){
				Log.error("Class Utils | Method setExcelFile | Exception desc : "+e.getMessage());
				DriverScript.bResult = false;
				}
			}

		public static String getCellData(int RowNum, int ColNum, String SheetName ) throws Exception{
			try{
				ExcelWSheet = ExcelWBook.getSheet(SheetName);
				Cell = ExcelWSheet.getRow(RowNum).getCell(ColNum);
				String CellData = Cell.getStringCellValue();
				return CellData;
			 }catch (Exception e){
				 Log.error("Class Utils | Method getCellData | Exception desc : "+e.getMessage());
				 DriverScript.bResult = false;
				 return"";
				 }
			 }

		public static int getRowCount(String SheetName){
			int iNumber=0;
			try {
				ExcelWSheet = ExcelWBook.getSheet(SheetName);
				iNumber=ExcelWSheet.getLastRowNum()+1;
			} catch (Exception e){
				Log.error("Class Utils | Method getRowCount | Exception desc : "+e.getMessage());
				DriverScript.bResult = false;
				}
			return iNumber;
			}

		public static int getRowContains(String sTestCaseName, int colNum,String SheetName) throws Exception{
			int iRowNum=0;	
			try {
				//ExcelWSheet = ExcelWBook.getSheet(SheetName);
				int rowCount = ExcelUtils.getRowCount(SheetName);
				for (; iRowNum<rowCount; iRowNum++){
					if  (ExcelUtils.getCellData(iRowNum,colNum,SheetName).equalsIgnoreCase(sTestCaseName)){
						break;
					}
				}       			
			} catch (Exception e){
				Log.error("Class Utils | Method getRowContains | Exception desc : "+e.getMessage());
				DriverScript.bResult = false;
				}
			return iRowNum;
			}

		public static int getTestStepsCount(String SheetName, String sTestCaseID, int iTestCaseStart) throws Exception{
			try {
				for(int i=iTestCaseStart;i<=ExcelUtils.getRowCount(SheetName);i++){
					if(!sTestCaseID.equals(ExcelUtils.getCellData(i, Constants.Col_TestCaseID, SheetName))){
						int number = i;
						return number;      				
						}
					}
				ExcelWSheet = ExcelWBook.getSheet(SheetName);
				int number=ExcelWSheet.getLastRowNum()+1;
				return number;
			} catch (Exception e){
				Log.error("Class Utils | Method getRowContains | Exception desc : "+e.getMessage());
				DriverScript.bResult = false;
				return 0;
			}
		}

	}
```

这都是为了框架中的异常处理。在测试结果报告的下一章中，我们将学习如何在 bresult 的值为'false'时将测试用例报告为失败。